exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-makecode

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Jekyll Theme MakeCode
description: MakeCode Primer is a Jekyll theme for GitHub Pages
